[package]
name = "stemfmt"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.46", features=["derive"]}
dirs = "6.0.0"
regex = "1.11.1"
serde = { version = "1.0.219", features = ["derive"]}
serde_json = "1.0.143"
